### ISSUE TITLE
treat "Sampling, filter, query or generator yielded no rows" as temporary failure

### ISSUE THREAD

**Issue by seamusabshere** [faradayio/bigml-rs#16]
```
ERROR: Problem while executing script: Error handling resource (Sampling, filter, query or generator yielded no rows (dataset/xxx))
CAUSE: {"code":-3050,"resource":"dataset/xxx"}
```

**Comment by seamusabshere** [comment]
another way to do this is allow a regex of error messages that should be treated as recoverable

e.g.

```
bigml-parallel [...] --allow-temporary-error 'Sampling, filter' [...]
```

**Comment by emk** [comment]
Interesting idea. It sounds like these errors are all internal to the WhizzML script in question.

I wonder wether it should be the responsibility of the script to recover from sampling operations using `try`/`catch`? The [manual](https://static.bigml.com/pdf/BigML_WhizzML_Reference.pdf?ver=8d98e3c) provides the following example:

> **2.10.3 Capturing Errors with try/catch**
> 
> WhizzML also includes syntactic sugar for handling errors via the try and catch keywords. `(try <body> (catch <id> <handler-body>))` executes `<body>` and, in case an error is raised, binds it to the variable `<id>` which is in the scope of
`<handler-body>`, to which control is transferred. In other words, the try/catch form is equivalent to
`(handle (lambda (<id>) <handler-body>) <body>)`
>
> For instance:
>
> ```clj
> (try
>   (log-info "Trying primary source")
>   (create-dataset {"source" "source/123678907959482245aa31"})
>   (catch e
>     (log-warn "Could not create primary source: " e)
>     (create-dataset {"source" "source/12345678901234567890abcd"})))
> ```

If we took this route, then:

1. `bigml-parallel` would be responsible for retrying network and BigML API errors.
2. WhizzML scripts would be responsible for retrying their own internal errors.

This would prevent `bigml-parallel` from having to know which internal WhizzML errors are "normal" and retriable, and which should be hard errors. Thoughts?

**Comment by fwallacevt** [comment]
That sounds reasonable to me.

**Comment by skelliest** [comment]
@seamus @fwallacevt Convo from Slack: We need need more information on the nature of the error to decide where to catch it. If a problem with bad inputs to an internal WhizzML function, then the WhizzML script will catch. Otherwise, WhizzML scripts should not catch.

**Comment by emk** [comment]
Something like this would work:
```clj
(define (retry count pause-msecs f)
  (if (< count 1)
    (f)
    (try
      (f)
      (catch e
        (log-warn "operation failed, will retry in " pause-msecs " milliseconds: " e)
        (sleep pause-msecs)
        (retry (- count 1) pause-msecs f)))))
```

This could be used as follows:

```clj
(define (create-scores) (create-and-wait-dataset {
  "origin_dataset" "dataset/5e7e0bd2c5f953217900d780"
  "all_fields" false
  ;; Specify the contents of our output fields using flatline JSON expressions.
  ;; This is basically a Lisp-like language for building new data.
  "new_fields" [
    { "name" "id" "field" ["field" "id"] }
    { "name" "score"
      ;; The `let` block here contains code snippets that we insert into the
      ;; flatline expression that we're building.
      "field" (let (conf ["field" "awesome confidence"]
                    phat 0.1) ;; Validated to be 0 < p < 1 at beginning of script
                ["if" ["=" conf 0]
                  0
                  ["/" phat
                     ["+" phat
                          ["/" ["*" ["-" 1 phat] ["-" 1 conf]]
                               conf]]]])}]}))
        
(define scores (retry 3 1000 create-scores))
```

Also tested on the console:

```clj
(define (buggy)
  (raise "This code is hopeless"))
  
(retry 3 500 buggy)
```

**Comment by emk** [comment]
`bigml-parallel` now includes `--retry-on` and `--retry-count` options that can be used to retry on specific script errors, because we've been seeing a lot of transient errors lately.
